project:
  type: website

website:
  title: "quarto-giscus-testing"
  comments:
    giscus:
      repo: andrewheiss/quarto-giscus-testing
  navbar:
    right:
      - about.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
