project:
  type: website

website:
  title: "quarto-giscus-testing"
  comments:
    giscus:
      repo: andrewheiss/quarto-giscus-testing
      category: General
      category-id: DIC_kwDOOa-qAc4CpLmu
      mapping: pathname
  navbar:
    right:
      - about.qmd
      - icon: github
        href: "https://github.com/andrewheiss/quarto-giscus-testing"
        aria-label: GitHub
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
